#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.

set -o errexit; set -o nounset

PRECOMMIT_CONFIG="../dotfiles-org/.pre-commit-config.yaml"

cd "$(dirname "$0")/.."

if [ -f "${PRECOMMIT_CONFIG}" ] && [ "$(uname -s)" = "Darwin" ]; then
  if ! brew list -1 | grep -q '^pre-commit$'; then
    echo "==> Installing pre-commit with Homebrew..."
    brew install pre-commit
  fi
fi

if ls ./*.tf 1> /dev/null 2>&1; then
  if ! brew list -1 | grep -q '^terraform$'; then
    echo "==> Installing Terraform with Homebrew..."
    brew install terraform
  fi
fi